services:
  db:
    container_name: postgres
    image: postgres:15.3
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=semantic
  app:
    container_name: api
    build: .
    ports:
      - "8000:8000"
    environment:
      - PGPASSWORD=admin
      - PGUSER=admin
      - PGHOST=db
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    depends_on:
      - db
